apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      # Trace 상세 화면 → Loki 로그 연동
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: false
        customQuery: false
        tags:
          - key: service.namespace
            value: service_namespace
          - key: service.name
            value: service_name
      nodeGraph:
        enabled: true
      # Loki 에서 검색 버튼으로 Tempo 로 이동
      lokiSearch:
        datasourceUid: loki
